user(john)
user(emma)
user(sarah)
user(michael)
user(alex)
user(lucy)
user(kevin)
user(rachel)
user(david)
user(lisa)

friend(john, emma)
friend(john, sarah)
friend(emma, sarah)
friend(michael, alex)
friend(michael, lucy)
friend(alex, lucy)
friend(kevin, rachel)
friend(kevin, david)
friend(rachel, david)